language: node_js
node_js:
  - 8
  - 10
cache: yarn
before_install:
  - npm install -g yo
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"
after_script: 'cat ./coverage/lcov.info | coveralls'
